version: "3.8"
services:
  db:
    image: postgres
    restart: always
    env_file: 
      - database.env
    ports: 
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

  app:
    build: app

volumes:
  database-data: