version: "3.8"
services:
  db:
    build: db
    restart: always
    env_file: 
      - db/database.env
    ports: 
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

  app:
    build: app
    depends_on:
      - db

volumes:
  database-data: