services:
  app:
    build: app
    container_name: tsl_event_etl
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0.4-focal
    container_name: tsl_event_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
        - ./initdb.d/:/docker-entrypoint-initdb.d/
        - ./data:/data/db/
